version: '3.8'
services:
  homeassistant:
    container_name: ${ENV_NAME}-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${HA_VERSION}"
    volumes:
      - ..:/config
    ports:
      - "${HOST_PORT}:8123"
    environment:
      - MARIADB_URL=mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${HOST_IP}:${MARIADB_PORT}/${MARIADB_DATABASE}?charset=utf8mb4
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    user: vscode:vscode
    restart: unless-stopped
    # Official HA Containerized runs privileged. Potentially easier for cross-platform integration with host USB sticks, etc but generally considered security risk.
    privileged: false
    depends_on:
      mariadb:
        condition: service_healthy
      mosquitto:
        condition: service_started

  mariadb:
    container_name: ${ENV_NAME}-mariadb
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1 # auto upgrade database when deploying new mariadb image version
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck: # test that the mysql has started and db exists before starting home assistant
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$${MARIADB_ROOT_PASSWORD}" ]
      interval: 20s
      timeout: 5s
      retries: 25 # it may take 5 mins for a clean install to reach healthy
      start_period: 30s

  mosquitto:
    container_name: ${ENV_NAME}-mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "${MOSQUITTO_LISTENER_PORT}:1883"
      - "${MOSQUITTO_WEBSOCKET_PORT}:9001"
    environment:
      - MOSQUITTO_USER=${MOSQUITTO_USER}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000      
    restart: unless-stopped
    # for non-dev environment change mosquitto.conf to use a password file instead of the default anonymous access
    # commands to delete and re-create password.txt (if required) eg using docker/portainer terminal in and cd to the /mosquitto dir
    # rm -rf config/password.txt
    # echo "${MOSQUITTO_USER}:${MOSQUITTO_PASSWORD}" > config/password.txt
    # mosquitto_passwd -U config/password.txt

volumes:
  mariadb:
    